cargo-features = ["edition2024"]
[package]
name = "cybergear-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "0.3.10"
embassy-sync = "0.6.2"
embassy-time = "0.4.0"
embedded-can = "0.4.1"
nb = "1.1.0"


[dev-dependencies]
mockall = "0.13.1"
