[build]
target = "xtensa-esp32-none-elf"

# Apply the normal Rust toolchain for tests
[alias]
host-test = "test --lib --target x86_64-unknown-linux-gnu -- --show-output"

[test]
target = "x86_64-unknown-linux-gnu"
