/* automatically generated by rust-bindgen 0.71.1 */
#![allow(warnings, non_camel_case_types, non_upper_case_globals, non_snake_case)]
pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2Y: u32 = 0;
pub const __GLIBC_USE_ISOC23: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 32;
pub const __WORDSIZE32_SIZE_ULONG: u32 = 0;
pub const __WORDSIZE32_PTRDIFF_LONG: u32 = 0;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __TIMESIZE: u32 = 32;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C23_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 41;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C23: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 0;
pub const __STATFS_MATCHES_STATFS64: u32 = 0;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 0;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i32 = -2147483648;
pub const INT_FAST32_MIN: i32 = -2147483648;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u32 = 2147483647;
pub const INT_FAST32_MAX: u32 = 2147483647;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: u32 = 4294967295;
pub const UINT_FAST32_MAX: u32 = 4294967295;
pub const INTPTR_MIN: i32 = -2147483648;
pub const INTPTR_MAX: u32 = 2147483647;
pub const UINTPTR_MAX: u32 = 4294967295;
pub const PTRDIFF_MIN: i32 = -2147483648;
pub const PTRDIFF_MAX: u32 = 2147483647;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: u32 = 4294967295;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type __u_char = ::core::ffi::c_uchar;
pub type __u_short = ::core::ffi::c_ushort;
pub type __u_int = ::core::ffi::c_uint;
pub type __u_long = ::core::ffi::c_ulong;
pub type __int8_t = ::core::ffi::c_schar;
pub type __uint8_t = ::core::ffi::c_uchar;
pub type __int16_t = ::core::ffi::c_short;
pub type __uint16_t = ::core::ffi::c_ushort;
pub type __int32_t = ::core::ffi::c_int;
pub type __uint32_t = ::core::ffi::c_uint;
pub type __int64_t = ::core::ffi::c_longlong;
pub type __uint64_t = ::core::ffi::c_ulonglong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::core::ffi::c_longlong;
pub type __u_quad_t = ::core::ffi::c_ulonglong;
pub type __intmax_t = ::core::ffi::c_longlong;
pub type __uintmax_t = ::core::ffi::c_ulonglong;
pub type __dev_t = __uint64_t;
pub type __uid_t = ::core::ffi::c_uint;
pub type __gid_t = ::core::ffi::c_uint;
pub type __ino_t = ::core::ffi::c_ulong;
pub type __ino64_t = __uint64_t;
pub type __mode_t = ::core::ffi::c_uint;
pub type __nlink_t = ::core::ffi::c_uint;
pub type __off_t = ::core::ffi::c_long;
pub type __off64_t = __int64_t;
pub type __pid_t = ::core::ffi::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::core::ffi::c_int; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __fsid_t"][::core::mem::size_of::<__fsid_t>() - 8usize];
    ["Alignment of __fsid_t"][::core::mem::align_of::<__fsid_t>() - 4usize];
    ["Offset of field: __fsid_t::__val"][::core::mem::offset_of!(__fsid_t, __val) - 0usize];
};
pub type __clock_t = ::core::ffi::c_long;
pub type __rlim_t = ::core::ffi::c_ulong;
pub type __rlim64_t = __uint64_t;
pub type __id_t = ::core::ffi::c_uint;
pub type __time_t = ::core::ffi::c_long;
pub type __useconds_t = ::core::ffi::c_uint;
pub type __suseconds_t = ::core::ffi::c_long;
pub type __suseconds64_t = __int64_t;
pub type __daddr_t = ::core::ffi::c_int;
pub type __key_t = ::core::ffi::c_int;
pub type __clockid_t = ::core::ffi::c_int;
pub type __timer_t = *mut ::core::ffi::c_void;
pub type __blksize_t = ::core::ffi::c_long;
pub type __blkcnt_t = ::core::ffi::c_long;
pub type __blkcnt64_t = __int64_t;
pub type __fsblkcnt_t = ::core::ffi::c_ulong;
pub type __fsblkcnt64_t = __uint64_t;
pub type __fsfilcnt_t = ::core::ffi::c_ulong;
pub type __fsfilcnt64_t = __uint64_t;
pub type __fsword_t = ::core::ffi::c_int;
pub type __ssize_t = ::core::ffi::c_int;
pub type __syscall_slong_t = ::core::ffi::c_long;
pub type __syscall_ulong_t = ::core::ffi::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::core::ffi::c_char;
pub type __intptr_t = ::core::ffi::c_int;
pub type __socklen_t = ::core::ffi::c_uint;
pub type __sig_atomic_t = ::core::ffi::c_int;
pub type __time64_t = __int64_t;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::core::ffi::c_schar;
pub type int_fast16_t = ::core::ffi::c_int;
pub type int_fast32_t = ::core::ffi::c_int;
pub type int_fast64_t = ::core::ffi::c_longlong;
pub type uint_fast8_t = ::core::ffi::c_uchar;
pub type uint_fast16_t = ::core::ffi::c_uint;
pub type uint_fast32_t = ::core::ffi::c_uint;
pub type uint_fast64_t = ::core::ffi::c_ulonglong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
#[doc = " Get device ID (communication type 0); Get device ID and 64-bit MCU unique identifier"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_FETCH_DEVICE_ID:
    cyber_gear_can_communication_type_t = 0;
#[doc = " Operation mode motor control command (communication type 1) is used to send control commands to the motor"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_MOTION_CONTROL_COMMAND:
    cyber_gear_can_communication_type_t = 1;
#[doc = " Motor feedback data (communication type 2) is used to feedback the motor operation status to the host"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_STATUS_REPORT:
    cyber_gear_can_communication_type_t = 2;
#[doc = " Motor enable operation (communication type 3)"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_ENABLE_DEVICE:
    cyber_gear_can_communication_type_t = 3;
#[doc = " Motor stop operation (communication type 4)"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_DISABLE_DEVICE:
    cyber_gear_can_communication_type_t = 4;
#[doc = " Setting the motor mechanical zero position (communication type 6) will set the current motor position to the mechanical zero position (power-off loss)"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_SET_MECHANICAL_ZERO_POSITION:
    cyber_gear_can_communication_type_t = 6;
#[doc = " Set the motor CAN_ID (communication type 7) to change the current motor CAN_ID, effective immediately."]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_SET_CAN_ID:
    cyber_gear_can_communication_type_t = 7;
#[doc = " Request Logging data."]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_LOGGING:
    cyber_gear_can_communication_type_t = 10;
#[doc = " Single parameter read (communication type 17)"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_READ_SINGLE_PARAM:
    cyber_gear_can_communication_type_t = 17;
#[doc = " Single parameter write (communication type 18) (power off loss)"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_WRITE_SINGLE_PARAM:
    cyber_gear_can_communication_type_t = 18;
#[doc = " Fault feedback frame (communication type 21)"]
pub const cyber_gear_can_communication_type_t_COMMUNICATION_ERROR_REPORT:
    cyber_gear_can_communication_type_t = 21;
pub type cyber_gear_can_communication_type_t = ::core::ffi::c_uint;
#[doc = " Name Motor name\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_WR_NAME: cyber_gear_config_index_t = 0;
#[doc = " BarCode\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_BAR_CODE: cyber_gear_config_index_t = 1;
#[doc = " BootCodeVersion\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_BOOT_CODE_VERSION: cyber_gear_config_index_t = 4096;
#[doc = " BootBuildDate\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_BOOT_BUILD_DATE: cyber_gear_config_index_t = 4097;
#[doc = " BootBuildTime\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_BOOT_BUILD_TIME: cyber_gear_config_index_t = 4098;
#[doc = " AppCodeVersion\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_APP_CODE_VERSION: cyber_gear_config_index_t = 4099;
#[doc = " AppGitVersion\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_APP_GIT_VERSION: cyber_gear_config_index_t = 4100;
#[doc = " AppBuildDate\n Parameter type String"]
pub const cyber_gear_config_index_t_CONFIG_R_APP_BUILD_DATE: cyber_gear_config_index_t = 4101;
#[doc = " AppBuildTime\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_APP_BUILD_TIME: cyber_gear_config_index_t = 4102;
#[doc = " AppCodeName\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_APP_CODE_NAME: cyber_gear_config_index_t = 4103;
#[doc = " echoPara1\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_ECHO_PARA1: cyber_gear_config_index_t = 8192;
#[doc = " echoPara2\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_ECHO_PARA2: cyber_gear_config_index_t = 8193;
#[doc = " echoPara3\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_ECHO_PARA3: cyber_gear_config_index_t = 8194;
#[doc = " echoPara4\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_ECHO_PARA4: cyber_gear_config_index_t = 8195;
#[doc = " echoFreHz\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_WR_ECHO_FRE_HZ: cyber_gear_config_index_t = 8196;
#[doc = " MechOffset Motor encoder angle offset\n Parameter type float [-7, 7]"]
pub const cyber_gear_config_index_t_CONFIG_R_MECH_OFFSET: cyber_gear_config_index_t = 8197;
#[doc = " MechPos_init Reference angle for initial multi-turn\n Parameter type float [-50, 50]"]
pub const cyber_gear_config_index_t_CONFIG_WR_MECH_POS_INIT: cyber_gear_config_index_t = 8198;
#[doc = " limit_torque torque limit\n Parameter type float [0, 12]"]
pub const cyber_gear_config_index_t_CONFIG_WR_LIMIT_TORQUE: cyber_gear_config_index_t = 8199;
#[doc = " I_FW_MAX weak magnetic current value, default 0\n Parameter type float [0, 33]"]
pub const cyber_gear_config_index_t_CONFIG_WR_I_FW_MAX: cyber_gear_config_index_t = 8200;
#[doc = " motor_index motor index, marking the motor joint position\n Parameter type uint8_t [0, 20]"]
pub const cyber_gear_config_index_t_CONFIG_WR_MOTOR_INDEX: cyber_gear_config_index_t = 8201;
#[doc = " CAN_ID local node id\n Parameter type uint8_t [0, 127]"]
pub const cyber_gear_config_index_t_CONFIG_WR_CAN_ID: cyber_gear_config_index_t = 8202;
#[doc = " CAN_MASTER can Host id\n Parameter type uint8_t [0, 127]"]
pub const cyber_gear_config_index_t_CONFIG_WR_CAN_MASTER: cyber_gear_config_index_t = 8203;
#[doc = " CAN_TIMEOUT can timeout threshold, default 0\n Parameter type uint32_t [0, 10000]"]
pub const cyber_gear_config_index_t_CONFIG_WR_CAN_TIMEOUT: cyber_gear_config_index_t = 8204;
#[doc = " motorOverTemp motor protection temperature value, temp (degrees) *10\n Parameter type uint16_t [0, 1500]"]
pub const cyber_gear_config_index_t_CONFIG_WR_MOTOR_OVER_TEMP: cyber_gear_config_index_t = 8205;
#[doc = " overTempTime over temperature time\n Parameter type uint32_t [0, 100000]"]
pub const cyber_gear_config_index_t_CONFIG_WR_OVER_TEMP_TIME: cyber_gear_config_index_t = 8206;
#[doc = " GearRatio gear ratio\n Parameter type float [1, 64]"]
pub const cyber_gear_config_index_t_CONFIG_WR_GEAR_RATIO: cyber_gear_config_index_t = 8207;
#[doc = " Tq_caliType torque calibration method setting\n parameter type uint8_t 0, 1"]
pub const cyber_gear_config_index_t_CONFIG_WR_TQ_CALI_TYPE: cyber_gear_config_index_t = 8208;
#[doc = " cur_filt_gain current filter parameter\n parameter type float [0, 1]"]
pub const cyber_gear_config_index_t_CONFIG_WR_CUR_FILT_GAIN: cyber_gear_config_index_t = 8209;
#[doc = " cur_kp current kp\n parameter type float [0, 200]"]
pub const cyber_gear_config_index_t_CONFIG_WR_CUR_KP: cyber_gear_config_index_t = 8210;
#[doc = " cur_ki current ki\n parameter type float [0, 200]"]
pub const cyber_gear_config_index_t_CONFIG_WR_CUR_KI: cyber_gear_config_index_t = 8211;
#[doc = " spd_kp speed kp\n parameter type float [0, 200]"]
pub const cyber_gear_config_index_t_CONFIG_WR_SPD_KP: cyber_gear_config_index_t = 8212;
#[doc = " spd_ki speed ki\n parameter type float [0, 200]"]
pub const cyber_gear_config_index_t_CONFIG_WR_SPD_KI: cyber_gear_config_index_t = 8213;
#[doc = " loc_kp position kp\n parameter type float [0, 200]"]
pub const cyber_gear_config_index_t_CONFIG_WR_LOC_KP: cyber_gear_config_index_t = 8214;
#[doc = " spd_filt_gain speed filter parameter\n parameter type float [0, 1]"]
pub const cyber_gear_config_index_t_CONFIG_WR_SPD_FILT_GAIN: cyber_gear_config_index_t = 8215;
#[doc = " limit_spd position loop speed limit\n parameter type float [0, 200]"]
pub const cyber_gear_config_index_t_CONFIG_WR_LIMIT_SPD: cyber_gear_config_index_t = 8216;
#[doc = " limit_cur position speed control current limit\n parameter type float [0, 27]"]
pub const cyber_gear_config_index_t_CONFIG_WR_LIMIT_CUR: cyber_gear_config_index_t = 8217;
#[doc = " timeUse0\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_TIME_USE0: cyber_gear_config_index_t = 12288;
#[doc = " timeUse1\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_TIME_USE1: cyber_gear_config_index_t = 12289;
#[doc = " timeUse1\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_TIME_USE2: cyber_gear_config_index_t = 12290;
#[doc = " timeUse1\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_TIME_USE3: cyber_gear_config_index_t = 12291;
#[doc = " encoderRaw magnetic encoder sampling value\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_ENCODER_RAW: cyber_gear_config_index_t = 12292;
#[doc = " mcuTemp mcu internal temperature, *10\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_MCU_TEMP: cyber_gear_config_index_t = 12293;
#[doc = " motorTemp motor ntc temperature, *10\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_MOTOR_TEMP: cyber_gear_config_index_t = 12294;
#[doc = " vBus(mv) bus voltage\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_VBUS_MV: cyber_gear_config_index_t = 12295;
#[doc = " adc1Offset adc sampling channel 1 zero current offset\n parameter type int32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_ADC1_OFFSET: cyber_gear_config_index_t = 12296;
#[doc = " adc2Offset adc sampling channel 2 zero current offset\n parameter type int32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_ADC2_OFFSET: cyber_gear_config_index_t = 12297;
#[doc = " adc1Raw adc sampling value 1\n parameter type uint32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_ADC1_RAW: cyber_gear_config_index_t = 12298;
#[doc = " adc2Raw adc sampling value 2\n parameter type uint32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_ADC2_RAW: cyber_gear_config_index_t = 12299;
#[doc = " VBUS bus voltage V\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_VBUS_V: cyber_gear_config_index_t = 12300;
#[doc = " cmdId id ring instruction, A\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_ID: cyber_gear_config_index_t = 12301;
#[doc = " cmdIq iq ring instruction, A\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_IQ: cyber_gear_config_index_t = 12302;
#[doc = " cmdlocref Position loop command, rad\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_LOC_REF: cyber_gear_config_index_t = 12303;
#[doc = " cmdspdref Speed \u{200b}\u{200b}loop command, rad/s\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_SPD_REF: cyber_gear_config_index_t = 12304;
#[doc = " cmdTorque Torque command, nm\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_TORQUE: cyber_gear_config_index_t = 12305;
#[doc = " cmdPos mit protocol angle command\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_POS: cyber_gear_config_index_t = 12306;
#[doc = " cmdVel mit protocol velocity command\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CMD_VEL: cyber_gear_config_index_t = 12307;
#[doc = " rotation Number of revolutions\n Parameter type int16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_ROTATION: cyber_gear_config_index_t = 12308;
#[doc = " modPos Mechanical angle of motor without counting turns, rad\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_MOD_POS: cyber_gear_config_index_t = 12309;
#[doc = " mechPos Mechanical angle of load end counting turns, rad\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_MECH_POS: cyber_gear_config_index_t = 12310;
#[doc = " mechVel Load end speed, rad/s\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_MECH_VEL: cyber_gear_config_index_t = 12311;
#[doc = " elecPos Electrical angle\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_ELEC_POS: cyber_gear_config_index_t = 12312;
#[doc = " ia U line current, A\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_IA: cyber_gear_config_index_t = 12313;
#[doc = " ib V line current, A\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_IB: cyber_gear_config_index_t = 12314;
#[doc = " ic W line current, A\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_IC: cyber_gear_config_index_t = 12315;
#[doc = " tick\n parameter type uint32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_TICK: cyber_gear_config_index_t = 12316;
#[doc = " phaseOrder calibration direction mark\n parameter type uint8_t"]
pub const cyber_gear_config_index_t_CONFIG_R_PHASE_ORDER: cyber_gear_config_index_t = 12317;
#[doc = " iqf iq filter value, A\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_IQF: cyber_gear_config_index_t = 12318;
#[doc = " boardTemp board temperature, *10\n parameter type int16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_BOARD_TEMP: cyber_gear_config_index_t = 12319;
#[doc = " iq iq original value, A\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_IQ: cyber_gear_config_index_t = 12320;
#[doc = " id id original value, A\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_ID: cyber_gear_config_index_t = 12321;
#[doc = " faultSta fault status value\n parameter type uint32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_FAULT_STATUS: cyber_gear_config_index_t = 12322;
#[doc = " warnSta warning status value\n parameter type uint32_t"]
pub const cyber_gear_config_index_t_CONFIG_R_WARN_STATUS: cyber_gear_config_index_t = 12323;
#[doc = " drv_fault driver chip fault value\n parameter type uint16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_DRV_FAULT: cyber_gear_config_index_t = 12324;
#[doc = " drv_temp driver chip temperature value, degrees\n parameter type int16_t"]
pub const cyber_gear_config_index_t_CONFIG_R_DRV_TEMP: cyber_gear_config_index_t = 12325;
#[doc = " Uq q axis voltage\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_UQ: cyber_gear_config_index_t = 12326;
#[doc = " Ud d-axis voltage\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_UD: cyber_gear_config_index_t = 12327;
#[doc = " dtc_u U-phase output duty cycle\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_DTC_U: cyber_gear_config_index_t = 12328;
#[doc = " dtc_v V-phase output duty cycle\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_DTC_V: cyber_gear_config_index_t = 12329;
#[doc = " dtc_w W-phase output duty cycle\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_DTC_W: cyber_gear_config_index_t = 12330;
#[doc = " v_bus closed loop vbus\n Parameter type"]
pub const cyber_gear_config_index_t_CONFIG_R_CLOSED_LOOP_V_BUS: cyber_gear_config_index_t = 12331;
#[doc = " v_ref closed loop vq,vd composite voltage\n Parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_CLOSED_LOOP_V_REF: cyber_gear_config_index_t = 12332;
#[doc = " torque_fdb torque feedback value, nm\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_TORQUE_FDB: cyber_gear_config_index_t = 12333;
#[doc = " rated_i motor rated current\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_RATED_I: cyber_gear_config_index_t = 12334;
#[doc = " limit_i motor limit maximum current\n parameter type float"]
pub const cyber_gear_config_index_t_CONFIG_R_LIMIT_I: cyber_gear_config_index_t = 12335;
pub type cyber_gear_config_index_t = ::core::ffi::c_uint;
#[doc = " operation control mode\n 0: operation control mode 1: position mode 2: speed mode 3: current mode\n parameter type uint8_t\n parameter byte number 1\n parameter description"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_RUN_MODE:
    cyber_gear_read_write_parameter_index_t = 28677;
#[doc = " Current mode Iq command\n Parameter type float\n Parameter byte count 4\n Parameter description -27~27A"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_IQ_REF:
    cyber_gear_read_write_parameter_index_t = 28678;
#[doc = " Speed \u{200b}\u{200b}mode speed command\n Parameter type float\n Parameter byte count 4\n Parameter description -30~30rad/s"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_SPD_REF:
    cyber_gear_read_write_parameter_index_t = 28682;
#[doc = " Torque limit\n Parameter type float\n Parameter byte count 4\n Parameter description 0~12Nm"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_LIMIT_TORQUE:
    cyber_gear_read_write_parameter_index_t = 28683;
#[doc = " Current Kp\n Parameter type float\n Parameter byte count 4\n Parameter description Default value 0.125"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_CUR_KP:
    cyber_gear_read_write_parameter_index_t = 28688;
#[doc = " Current Ki\n Parameter type float\n Parameter byte count 4\n Parameter description Default value 0.0158"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_CUR_KI:
    cyber_gear_read_write_parameter_index_t = 28689;
#[doc = " Current filter coefficient filt_gain\n Parameter type float\n Parameter byte number 4\n Parameter description Default value 0~1.0, default value W/R 0.1"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_CUR_FILT_GAIN:
    cyber_gear_read_write_parameter_index_t = 28692;
#[doc = " Position mode angle command\n Parameter type float\n Parameter byte number 4\n Parameter description rad"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_LOC_REF:
    cyber_gear_read_write_parameter_index_t = 28694;
#[doc = " Position mode speed setting\n Parameter type float\n Parameter byte number 4\n Parameter description 0~30rad/s"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_LIMIT_SPD:
    cyber_gear_read_write_parameter_index_t = 28695;
#[doc = " Speed \u{200b}\u{200b}position mode current setting\n Parameter type float\n Parameter byte number 4\n Parameter description 0~27A"]
pub const cyber_gear_read_write_parameter_index_t_PARAMETER_LIMIT_CUR:
    cyber_gear_read_write_parameter_index_t = 28696;
pub type cyber_gear_read_write_parameter_index_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cyber_gear_can_t {
    pub can_id: cyber_gear_can_t__bindgen_ty_1,
    pub can_data: cyber_gear_can_t__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union cyber_gear_can_t__bindgen_ty_1 {
    pub value: u32,
    pub bytes: [u8; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_can_t__bindgen_ty_1"]
        [::core::mem::size_of::<cyber_gear_can_t__bindgen_ty_1>() - 4usize];
    ["Alignment of cyber_gear_can_t__bindgen_ty_1"]
        [::core::mem::align_of::<cyber_gear_can_t__bindgen_ty_1>() - 4usize];
    ["Offset of field: cyber_gear_can_t__bindgen_ty_1::value"]
        [::core::mem::offset_of!(cyber_gear_can_t__bindgen_ty_1, value) - 0usize];
    ["Offset of field: cyber_gear_can_t__bindgen_ty_1::bytes"]
        [::core::mem::offset_of!(cyber_gear_can_t__bindgen_ty_1, bytes) - 0usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union cyber_gear_can_t__bindgen_ty_2 {
    pub value: u64,
    pub bytes: [u8; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_can_t__bindgen_ty_2"]
        [::core::mem::size_of::<cyber_gear_can_t__bindgen_ty_2>() - 8usize];
    ["Alignment of cyber_gear_can_t__bindgen_ty_2"]
        [::core::mem::align_of::<cyber_gear_can_t__bindgen_ty_2>() - 8usize];
    ["Offset of field: cyber_gear_can_t__bindgen_ty_2::value"]
        [::core::mem::offset_of!(cyber_gear_can_t__bindgen_ty_2, value) - 0usize];
    ["Offset of field: cyber_gear_can_t__bindgen_ty_2::bytes"]
        [::core::mem::offset_of!(cyber_gear_can_t__bindgen_ty_2, bytes) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_can_t"][::core::mem::size_of::<cyber_gear_can_t>() - 16usize];
    ["Alignment of cyber_gear_can_t"][::core::mem::align_of::<cyber_gear_can_t>() - 8usize];
    ["Offset of field: cyber_gear_can_t::can_id"]
        [::core::mem::offset_of!(cyber_gear_can_t, can_id) - 0usize];
    ["Offset of field: cyber_gear_can_t::can_data"]
        [::core::mem::offset_of!(cyber_gear_can_t, can_data) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cyber_gear_motion_control_t {
    pub motor_can_id: u8,
    pub target_location: f32,
    pub target_speed: f32,
    pub kp: f32,
    pub kd: f32,
    pub torque: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_motion_control_t"]
        [::core::mem::size_of::<cyber_gear_motion_control_t>() - 24usize];
    ["Alignment of cyber_gear_motion_control_t"]
        [::core::mem::align_of::<cyber_gear_motion_control_t>() - 4usize];
    ["Offset of field: cyber_gear_motion_control_t::motor_can_id"]
        [::core::mem::offset_of!(cyber_gear_motion_control_t, motor_can_id) - 0usize];
    ["Offset of field: cyber_gear_motion_control_t::target_location"]
        [::core::mem::offset_of!(cyber_gear_motion_control_t, target_location) - 4usize];
    ["Offset of field: cyber_gear_motion_control_t::target_speed"]
        [::core::mem::offset_of!(cyber_gear_motion_control_t, target_speed) - 8usize];
    ["Offset of field: cyber_gear_motion_control_t::kp"]
        [::core::mem::offset_of!(cyber_gear_motion_control_t, kp) - 12usize];
    ["Offset of field: cyber_gear_motion_control_t::kd"]
        [::core::mem::offset_of!(cyber_gear_motion_control_t, kd) - 16usize];
    ["Offset of field: cyber_gear_motion_control_t::torque"]
        [::core::mem::offset_of!(cyber_gear_motion_control_t, torque) - 20usize];
};
pub const cyber_gear_motor_mode_t_MOTOR_MODE_RESET: cyber_gear_motor_mode_t = 0;
pub const cyber_gear_motor_mode_t_MOTOR_MODE_CALI: cyber_gear_motor_mode_t = 1;
pub const cyber_gear_motor_mode_t_MOTOR_MODE_MOTOR: cyber_gear_motor_mode_t = 2;
pub type cyber_gear_motor_mode_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone, Default)]
pub struct cyber_gear_motor_status_t {
    pub host_can_id: u8,
    pub motor_can_id: u8,
    pub current_torque: f32,
    pub current_location: f32,
    pub current_speed: f32,
    pub current_temperature: f32,
    pub has_calibration_error: ::core::ffi::c_int,
    pub has_hall_encode_error: ::core::ffi::c_int,
    pub has_magnetic_encoding_error: ::core::ffi::c_int,
    pub has_over_temperature: ::core::ffi::c_int,
    pub has_over_current: ::core::ffi::c_int,
    pub has_undervoltage: ::core::ffi::c_int,
    pub mode_type: cyber_gear_motor_mode_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_motor_status_t"]
        [::core::mem::size_of::<cyber_gear_motor_status_t>() - 48usize];
    ["Alignment of cyber_gear_motor_status_t"]
        [::core::mem::align_of::<cyber_gear_motor_status_t>() - 4usize];
    ["Offset of field: cyber_gear_motor_status_t::host_can_id"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, host_can_id) - 0usize];
    ["Offset of field: cyber_gear_motor_status_t::motor_can_id"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, motor_can_id) - 1usize];
    ["Offset of field: cyber_gear_motor_status_t::current_torque"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, current_torque) - 4usize];
    ["Offset of field: cyber_gear_motor_status_t::current_location"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, current_location) - 8usize];
    ["Offset of field: cyber_gear_motor_status_t::current_speed"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, current_speed) - 12usize];
    ["Offset of field: cyber_gear_motor_status_t::current_temperature"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, current_temperature) - 16usize];
    ["Offset of field: cyber_gear_motor_status_t::has_calibration_error"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, has_calibration_error) - 20usize];
    ["Offset of field: cyber_gear_motor_status_t::has_hall_encode_error"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, has_hall_encode_error) - 24usize];
    ["Offset of field: cyber_gear_motor_status_t::has_magnetic_encoding_error"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, has_magnetic_encoding_error) - 28usize];
    ["Offset of field: cyber_gear_motor_status_t::has_over_temperature"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, has_over_temperature) - 32usize];
    ["Offset of field: cyber_gear_motor_status_t::has_over_current"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, has_over_current) - 36usize];
    ["Offset of field: cyber_gear_motor_status_t::has_undervoltage"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, has_undervoltage) - 40usize];
    ["Offset of field: cyber_gear_motor_status_t::mode_type"]
        [::core::mem::offset_of!(cyber_gear_motor_status_t, mode_type) - 44usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct cyber_gear_single_parameter_t {
    pub host_can_id: u8,
    pub motor_can_id: u8,
    pub index: cyber_gear_read_write_parameter_index_t,
    pub data: cyber_gear_single_parameter_t__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union cyber_gear_single_parameter_t__bindgen_ty_1 {
    pub value: u32,
    pub bytes: [u8; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_single_parameter_t__bindgen_ty_1"]
        [::core::mem::size_of::<cyber_gear_single_parameter_t__bindgen_ty_1>() - 4usize];
    ["Alignment of cyber_gear_single_parameter_t__bindgen_ty_1"]
        [::core::mem::align_of::<cyber_gear_single_parameter_t__bindgen_ty_1>() - 4usize];
    ["Offset of field: cyber_gear_single_parameter_t__bindgen_ty_1::value"]
        [::core::mem::offset_of!(cyber_gear_single_parameter_t__bindgen_ty_1, value) - 0usize];
    ["Offset of field: cyber_gear_single_parameter_t__bindgen_ty_1::bytes"]
        [::core::mem::offset_of!(cyber_gear_single_parameter_t__bindgen_ty_1, bytes) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cyber_gear_single_parameter_t"]
        [::core::mem::size_of::<cyber_gear_single_parameter_t>() - 12usize];
    ["Alignment of cyber_gear_single_parameter_t"]
        [::core::mem::align_of::<cyber_gear_single_parameter_t>() - 4usize];
    ["Offset of field: cyber_gear_single_parameter_t::host_can_id"]
        [::core::mem::offset_of!(cyber_gear_single_parameter_t, host_can_id) - 0usize];
    ["Offset of field: cyber_gear_single_parameter_t::motor_can_id"]
        [::core::mem::offset_of!(cyber_gear_single_parameter_t, motor_can_id) - 1usize];
    ["Offset of field: cyber_gear_single_parameter_t::index"]
        [::core::mem::offset_of!(cyber_gear_single_parameter_t, index) - 4usize];
    ["Offset of field: cyber_gear_single_parameter_t::data"]
        [::core::mem::offset_of!(cyber_gear_single_parameter_t, data) - 8usize];
};
unsafe extern "C" {
    pub fn cyber_gear_can_init(frame: *const cyber_gear_can_t);
}
unsafe extern "C" {
    pub fn cyber_gear_can_dump(frame: *const cyber_gear_can_t);
}
unsafe extern "C" {
    pub fn cyber_gear_set_can_id_int_value(
        frame: *const cyber_gear_can_t,
        bit_start: ::core::ffi::c_int,
        bit_length: ::core::ffi::c_int,
        value: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_get_can_id_int_value(
        frame: *const cyber_gear_can_t,
        bit_start: ::core::ffi::c_int,
        bit_length: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn cyber_gear_set_can_id_communication_type(
        frame: *const cyber_gear_can_t,
        type_: cyber_gear_can_communication_type_t,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_set_can_id_communication_type_variant(
        frame: *const cyber_gear_can_t,
        type_: u8,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_set_can_id_host_can_id(
        frame: *const cyber_gear_can_t,
        value: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_set_can_id_target_can_id(
        frame: *const cyber_gear_can_t,
        value: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_build_parameter_write_frame_with_int_value(
        frame: *const cyber_gear_can_t,
        index: cyber_gear_read_write_parameter_index_t,
        value: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_build_parameter_write_frame_with_float_value(
        frame: *const cyber_gear_can_t,
        index: cyber_gear_read_write_parameter_index_t,
        value: f32,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_build_parameter_read_frame(
        frame: *const cyber_gear_can_t,
        index: cyber_gear_read_write_parameter_index_t,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_parse_parameter_read_frame(
        frame: *const cyber_gear_can_t,
    ) -> cyber_gear_single_parameter_t;
}
unsafe extern "C" {
    pub fn cyber_gear_get_can_id_communication_type(
        frame: *const cyber_gear_can_t,
    ) -> cyber_gear_can_communication_type_t;
}
unsafe extern "C" {
    pub fn cyber_gear_get_can_id_target_id(frame: *const cyber_gear_can_t) -> u8;
}
unsafe extern "C" {
    pub fn cyber_gear_get_can_id_host_id(frame: *const cyber_gear_can_t) -> u8;
}
unsafe extern "C" {
    pub fn cyber_gear_build_motion_control_frame(
        frame: *const cyber_gear_can_t,
        control_param: cyber_gear_motion_control_t,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_parse_motor_status_frame(
        frame: *const cyber_gear_can_t,
    ) -> cyber_gear_motor_status_t;
}
unsafe extern "C" {
    pub fn cyber_gear_build_set_mechanical_zero_position_frame(frame: *const cyber_gear_can_t);
}
unsafe extern "C" {
    pub fn cyber_gear_build_set_can_id_frame(
        frame: *const cyber_gear_can_t,
        setting_can_id: ::core::ffi::c_int,
    );
}
unsafe extern "C" {
    pub fn cyber_gear_dump_motor_status_frame(status: cyber_gear_motor_status_t);
}
